export const fonts = {
  spaceMonoRegular: 'SpaceMono-Regular',
  feather: 'feather',
  sfProDisplaySemibold: 'SFProDisplay-Semibold',
  sfProDisplayRegular: 'SFProDisplay-Regular',
  sfProDisplayBlackItalic: 'SFProDisplay-BlackItalic',
  sfProDisplayLight: 'SFProDisplay-Light',
  sfProDisplayMedium: 'SFProDisplay-Medium',
  featherAlt: 'Feather',
  sfProDisplayBoldItalic: 'SFProDisplay-BoldItalic',
  sfProDisplayThin: 'SFProDisplay-Thin',
  sfProDisplaySemiboldItalic: 'SFProDisplay-SemiboldItalic',
  sfProDisplayLightItalic: 'SFProDisplay-LightItalic',
  sfProDisplayHeavy: 'SFProDisplay-Heavy',
  sfProDisplayThinItalic: 'SFProDisplay-ThinItalic',
  sfProDisplayRegularItalic: 'SFProDisplay-RegularItalic',
  sfProDisplayBlack: 'SFProDisplay-Black',
  sfProDisplayUltralightItalic: 'SFProDisplay-UltralightItalic',
  sfProDisplayUltralight: 'SFProDisplay-Ultralight',
  sfProDisplayHeavyItalic: 'SFProDisplay-HeavyItalic',
  sfProDisplayMediumItalic: 'SFProDisplay-MediumItalic',
  sfProDisplayBold: 'SFProDisplay-Bold',
}
